# Generated by Django 3.1.1 on 2020-10-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactformemail',
            old_name='fromemail',
            new_name='email',
        ),
        migrations.AddField(
            model_name='contactformemail',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
