# Generated by Django 3.1.1 on 2020-10-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0005_auto_20201009_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
