# Generated by Django 3.1.1 on 2020-12-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0009_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ptotal',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
