# Generated by Django 3.1.1 on 2020-12-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0010_orderitem_ptotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformemail',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
