# Generated by Django 3.1.1 on 2020-12-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0011_auto_20201230_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformemail',
            name='contact',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
