# Generated by Django 3.1.1 on 2020-12-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0012_contactformemail_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='blulkorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=15)),
                ('ZipCode', models.IntegerField(max_length=7)),
                ('message', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField(max_length=10)),
            ],
        ),
    ]
