# Generated by Django 3.1.1 on 2020-12-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0013_blulkorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blulkorder',
            new_name='bulkorder',
        ),
    ]
