# Generated by Django 3.1.1 on 2020-12-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0014_auto_20201230_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkorder',
            name='ZipCode',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='bulkorder',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
