# Generated by Django 3.1.1 on 2021-01-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0015_auto_20201230_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkorder',
            name='product',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
